name: CMake

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Windows 10 SDK Action
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
      with:
        sdk-version: 22621

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout submodules
      shell: bash
      run: git submodule update --init --recursive
      
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        
    - name: Set VCPKG_ROOT
      run: |
        echo "VCPKG_ROOT=$(Get-Location)\vcpkg" >> $env:GITHUB_ENV
      shell: powershell
      
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/GWToolboxpp/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{runner.workspace}}/GWToolboxpp/build
      run: cmake $GITHUB_WORKSPACE --preset=vcpkg
      env:
        VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: Build
      working-directory: ${{runner.workspace}}/GWToolboxpp/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config RelWithDebInfo

    - name: Save output
      uses: actions/upload-artifact@v4
      with:
        path: ${{runner.workspace}}/GWToolboxpp/bin/RelWithDebInfo/
